### ISSUE TITLE
Does not copy when used with `snowpack build --watch`

### ISSUE THREAD

**Issue by IanVS** [donniean/snowpack-plugin-copy#1]
When I run in watch mode, the file is never copied to the build directory, although it works just fine when I'm not watching.

**Comment by IanVS** [comment]
I take it back, it does seem to work now, although I could swear I was having problems with this just a minute ago...  

If I'm able to reliably reproduce I'll reopen this.  Sorry for the noise, and thanks for the useful plugin!  I'm experimenting with using it for developing a browser extension, where I want to copy a manifest file into my `build` folder.  :)

**Comment by IanVS** [comment]
This seems to indeed be a limitation of snowpack itself: https://github.com/snowpackjs/snowpack/discussions/1905#discussioncomment-191112

**Comment by donniean** [comment]
😀  :)
